### ISSUE TITLE
Testing `tspa()`

### ISSUE THREAD

**Issue by marklhc** [Gengrui-Zhang/R2spa#3] opened 2022-02-15 22:51 UTC
Write a unit test for the `lavaan` example for the `tspa()` function.

- [ ] Test Multi-group version

**Comment by marklhc** [comment] 2022-04-15 05:13
@Gengrui-Zhang, please add back the "testthat.R" file as in [056d997](https://github.com/Gengrui-Zhang/R2spa/commit/056d9974872bbf7101809a45fe60cc6513000117). Name the test files in the format "test-xxx.R." See https://r-pkgs.org/tests.html#test-structure for more information.

**Comment by marklhc** [comment] 2022-04-15 05:20
I just restored the file, so that part is taken care of.

**Comment by marklhc** [comment] 2022-07-26 21:49
As an update, I got this error when running the `test-tspa` file. Could you check, @Gengrui-Zhang? Thank you.

```
Error (test-tspa.R:87:5): (code run outside of `test_that()`)
Error in `cfa_output_single$PE`: $ operator is invalid for atomic vectors
Backtrace:
 1. base::as.data.frame(cfa_output_single$PE)
      at test-tspa.R:87:4
```

**Comment by Gengrui-Zhang** [comment] 2022-08-02 19:58
Hi Mark @marklhc, I have checked the error and I think it should be related to my version of R. I have updated R, as well as all the packages. I think the specific error is the name of "PE" data frame changed to lower cases (i.e., "pe"). Thus the variable created from this data frame became invalid/null data frame. I have fixed that and also adapted some tests related to the reliability scores from `get_fs()`. Now the `test-tspa` file should have only failed tests (28 failures) but not errors. Thanks!

**Comment by marklhc** [comment] 2022-08-05 01:27
Thanks @Gengrui-Zhang. It's generally safer to use `lavaan::coef()` to extract coefficients. I have checked and edited the `test-tspa.R` file, with some comments added. Could you take a look and let me know what you think and if you have any questions? I basically try to reduce redundancy. If things are fine with you, could you also update the multiple-group section of that file, according to what I did for the single-group with two variables section? Note that the numbers for standard errors need to be updated with the change in the `get_fs()` output. Currently I still get an error 

```
Error (test-tspa.R:486:5): (code run outside of `test_that()`)
Error in `cfa_output_multi$pe`: $ operator is invalid for atomic vectors
Backtrace:
 1. base::as.data.frame(cfa_output_multi$pe)
      at test-tspa.R:486:4
```

Thank you.

**Comment by Gengrui-Zhang** [comment] 2022-08-08 11:41
Hi @marklhc. Thanks so much for cleaning the file and letting me know your techniques and thoughts. I believe they are really insightful and helpful to me and I have no arguments with your revision. One thing I want to let you know is that in multi-example testing, I set the expected value to .08 because .01 resulted in a failed test. 

`    # A set of .01 results in a failed test. I set it to .08 here
    test_that("test if the se of regression coefficients are similar for two methods",
              {
                expect_lt(
                  max(abs(sem_path_multi$se - tspa_path_multi$se)),
                  expected = .08
                )
              })`

Besides, I have one question and just wanna confirm I got a right understanding:

`# HL: Use vcov()'
JZ: I have one question here. Do equal vcov() results mean the standard error
      and regression coefficients are equal for two methods? I believe this is because
      regression coefficents and se are calculated from var/cov matrix?`

Last, regarding the error, I have rechecked and the test file ran without error on my side. Please let me know if this error occurs again and I'll fix it. Thanks!

**Comment by marklhc** [comment] 2022-08-08 15:04
@Gengrui-Zhang, thanks for the update. For the multi-group example, because you're comparing the results `tspa()` and manually writing the 2spa model, **their results should be identical**, not just that they are close (see my first example). If you find them to be not, that either means something's wrong with `tspa()` or the way you set up the model. As I mentioned, `get_fs()` now computes different standard errors than before, so your syntax should be updated, as well as the input for the standard errors.

The standard error is the square root of the diagonal elements of the covariance matrix for the estimator. The diagonal elements are the sampling variance (see e.g., [this thread on StackOverflow](https://stackoverflow.com/questions/52275542/how-to-calculate-the-standard-error-from-a-variance-covariance-matrix) or [this blog post by myself](https://quantscience.rbind.io/2020/04/11/cfa-standard-error/)).

**Comment by Gengrui-Zhang** [comment] 2022-08-08 21:34
@marklhc Hi Mark, thanks for the clarification and reminder. I have updated the model information and now everything should work well. I'll keep working on `test-get_fs()` and give you an update soon. Thanks!

**Comment by marklhc** [comment] 2022-08-09 04:50
Thanks @Gengrui-Zhang. I've changed the tests to use `expect_equal()`, as I've mentioned before. Once you have a chance to review and okay the changes, you may close the issue.

**Comment by Gengrui-Zhang** [comment] 2022-08-09 09:51
Hi @marklhc , thanks for the change. I believe everything looks great so far. I'll close the issue.

**Closed as completed** 2022-08-09 09:51 UTC
